export default function Head() {
  return (
    <>
      <title>GuGiSeK - passionate in IT</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="theme-color" content="#d6d6d6" />
      <link rel="icon" href="/img/favicon.png" />
    </>
  )
}
